package model.response;

/**
 *
 * @author asael
 */
public enum TipoRespuesta {
    LOGIN_USUARIO, CREAR_USUARIO, MODIFICAR_USUARIO, ELIMINAR_USUARIO, NUEVO_FORMULARIO,
    ELIMINAR_FORMULARIO, MODIFICAR_FORMUALARIO, AGREGAR_COMPONENTE, MODIFICAR_COMPONENTE,
    ELIMINAR_COMPONENTE;
}
