
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.sintactico;

/** CUP generated class containing symbol constants. */
public class StorageSym {
  /* terminals */
  public static final int PARAM_ID = 13;
  public static final int PARAM_ALINEACION = 23;
  public static final int PARAM_TEXTO_VISIBLE = 22;
  public static final int ENTERO = 46;
  public static final int SI = 41;
  public static final int WHITE = 50;
  public static final int CLASS_RADIO = 32;
  public static final int PARAM_CLASE = 21;
  public static final int IZQUIERDA = 38;
  public static final int FECHA = 45;
  public static final int CLASS_CHECKBOX = 31;
  public static final int INICIO_USER = 2;
  public static final int CLASS_COMBO = 35;
  public static final int PARAM_TEMA = 16;
  public static final int PARAM_NOMBRE_CAMPO = 19;
  public static final int CLOSE_ROUND_BRACKET = 9;
  public static final int COMMA = 5;
  public static final int CENTRO = 37;
  public static final int INICIO_FORM = 3;
  public static final int PARAM_FORMULARIO = 20;
  public static final int PARAM_COMPONENTES = 18;
  public static final int CLASS_CAMPO_TEXTO = 29;
  public static final int PARAM_URL = 28;
  public static final int ID = 44;
  public static final int EOF = 0;
  public static final int PARAM_FECHA_CREACION = 12;
  public static final int CLASS_BOTON = 36;
  public static final int PARAM_TITULO_FORM = 14;
  public static final int PARAM_NOMBRE_FORM = 15;
  public static final int error = 1;
  public static final int PARAM_PASSWORD = 11;
  public static final int OPEN_BRACE = 6;
  public static final int PARAM_FILAS = 26;
  public static final int CLASS_AREA_TEXTO = 30;
  public static final int CLASS_IMAGEN = 34;
  public static final int PARAM_USUARIO_CREACION = 17;
  public static final int LITERAL = 48;
  public static final int COLON = 4;
  public static final int NO = 42;
  public static final int DERECHA = 39;
  public static final int CLASS_FICHERO = 33;
  public static final int PARAM_COLUMNAS = 27;
  public static final int DARK = 49;
  public static final int OPEN_ROUND_BRACKET = 8;
  public static final int CLOSE_BRACE = 7;
  public static final int VALUE = 47;
  public static final int PARAM_OPCIONES = 25;
  public static final int PARAM_REQUERIDO = 24;
  public static final int JUSTIFICAR = 40;
  public static final int PARAM_USUARIO = 10;
  public static final int OPCIONES = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_USER",
  "INICIO_FORM",
  "COLON",
  "COMMA",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "OPEN_ROUND_BRACKET",
  "CLOSE_ROUND_BRACKET",
  "PARAM_USUARIO",
  "PARAM_PASSWORD",
  "PARAM_FECHA_CREACION",
  "PARAM_ID",
  "PARAM_TITULO_FORM",
  "PARAM_NOMBRE_FORM",
  "PARAM_TEMA",
  "PARAM_USUARIO_CREACION",
  "PARAM_COMPONENTES",
  "PARAM_NOMBRE_CAMPO",
  "PARAM_FORMULARIO",
  "PARAM_CLASE",
  "PARAM_TEXTO_VISIBLE",
  "PARAM_ALINEACION",
  "PARAM_REQUERIDO",
  "PARAM_OPCIONES",
  "PARAM_FILAS",
  "PARAM_COLUMNAS",
  "PARAM_URL",
  "CLASS_CAMPO_TEXTO",
  "CLASS_AREA_TEXTO",
  "CLASS_CHECKBOX",
  "CLASS_RADIO",
  "CLASS_FICHERO",
  "CLASS_IMAGEN",
  "CLASS_COMBO",
  "CLASS_BOTON",
  "CENTRO",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR",
  "SI",
  "NO",
  "OPCIONES",
  "ID",
  "FECHA",
  "ENTERO",
  "VALUE",
  "LITERAL",
  "DARK",
  "WHITE"
  };
}

