
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.l2ashdz.appcliente.analizadores.sintactico;

/** CUP generated class containing symbol constants. */
public class ReportsSym {
  /* terminals */
  public static final int WHERE = 5;
  public static final int CLOSE_BRACKET = 11;
  public static final int AND = 6;
  public static final int CADENA = 22;
  public static final int SELECT = 2;
  public static final int OR = 7;
  public static final int GREATER_THAN = 15;
  public static final int NOT = 8;
  public static final int NAME = 23;
  public static final int ID = 20;
  public static final int FORM = 4;
  public static final int OPEN_BRACKET = 10;
  public static final int EQUAL_TO = 16;
  public static final int NOT_EQUAL_TO = 19;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int LESS_THAN = 14;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int ARROW = 9;
  public static final int GREATER_THAN_OR_EQUAL_TO = 18;
  public static final int TO = 3;
  public static final int LESS_THAN_OR_EQUAL_TO = 17;
  public static final int APOSTROPHE = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "TO",
  "FORM",
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "ARROW",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "COMMA",
  "APOSTROPHE",
  "LESS_THAN",
  "GREATER_THAN",
  "EQUAL_TO",
  "LESS_THAN_OR_EQUAL_TO",
  "GREATER_THAN_OR_EQUAL_TO",
  "NOT_EQUAL_TO",
  "ID",
  "NUMERO",
  "CADENA",
  "NAME"
  };
}

