
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.l2ashdz.appcliente.analizadores.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSE_BRACKET = 27;
  public static final int OPEN_BRACE = 24;
  public static final int END_REQUESTS = 5;
  public static final int PARAM_OLD_USER = 15;
  public static final int PARAM_PASSWORD = 12;
  public static final int LOGIN = 7;
  public static final int PARAM_NEW_PASSWORD = 17;
  public static final int GREATER_THAN = 19;
  public static final int QUOTE_MARK = 21;
  public static final int VALUE = 28;
  public static final int START_REQUESTS = 3;
  public static final int CREATE_USER = 8;
  public static final int START_REQUEST = 2;
  public static final int MODIFY_USER = 10;
  public static final int COLON = 22;
  public static final int OPEN_BRACKET = 26;
  public static final int DELETE_USER = 9;
  public static final int USER_CREDENTIALS = 6;
  public static final int PARAM_FECHA_MODIFICACION = 14;
  public static final int COMMA = 23;
  public static final int EOF = 0;
  public static final int LESS_THAN = 18;
  public static final int CLOSE_BRACE = 25;
  public static final int EXCLAMATION_MARK = 20;
  public static final int error = 1;
  public static final int PARAM_FECHA_CREACION = 13;
  public static final int PARAM_USUARIO = 11;
  public static final int END_REQUEST = 4;
  public static final int PARAM_NEW_USER = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "START_REQUEST",
  "START_REQUESTS",
  "END_REQUEST",
  "END_REQUESTS",
  "USER_CREDENTIALS",
  "LOGIN",
  "CREATE_USER",
  "DELETE_USER",
  "MODIFY_USER",
  "PARAM_USUARIO",
  "PARAM_PASSWORD",
  "PARAM_FECHA_CREACION",
  "PARAM_FECHA_MODIFICACION",
  "PARAM_OLD_USER",
  "PARAM_NEW_USER",
  "PARAM_NEW_PASSWORD",
  "LESS_THAN",
  "GREATER_THAN",
  "EXCLAMATION_MARK",
  "QUOTE_MARK",
  "COLON",
  "COMMA",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "VALUE"
  };
}

