
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.l2ashdz.appcliente.analizador.sintactico;

/** CUP generated class containing symbol constants. */
public class ResponseSym {
  /* terminals */
  public static final int CLOSE_BRACKET = 30;
  public static final int OPEN_BRACE = 27;
  public static final int PARAM_STATE = 17;
  public static final int NEW_FORM = 11;
  public static final int START_RESPONSE = 2;
  public static final int LOGIN = 7;
  public static final int GREATER_THAN = 23;
  public static final int PARAM_LOGGED_USER = 19;
  public static final int DELETE_COMPONENT = 15;
  public static final int VALUE = 31;
  public static final int SUCCES = 20;
  public static final int CREATE_USER = 8;
  public static final int ERROR = 21;
  public static final int MODIFY_USER = 10;
  public static final int EDIT_COMPONENT = 16;
  public static final int LITERAL = 32;
  public static final int COLON = 25;
  public static final int MODIFY_FORM = 13;
  public static final int OPEN_BRACKET = 29;
  public static final int DELETE_USER = 9;
  public static final int RESPONSE_PARAMS = 6;
  public static final int COMMA = 26;
  public static final int DELETE_FORM = 12;
  public static final int EOF = 0;
  public static final int LESS_THAN = 22;
  public static final int CLOSE_BRACE = 28;
  public static final int PARAM_MESSAGE = 18;
  public static final int START_RESPONSES = 4;
  public static final int EXCLAMATION_MARK = 24;
  public static final int error = 1;
  public static final int END_RESPONSES = 5;
  public static final int NEW_COMPONENT = 14;
  public static final int END_RESPONSE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "START_RESPONSE",
  "END_RESPONSE",
  "START_RESPONSES",
  "END_RESPONSES",
  "RESPONSE_PARAMS",
  "LOGIN",
  "CREATE_USER",
  "DELETE_USER",
  "MODIFY_USER",
  "NEW_FORM",
  "DELETE_FORM",
  "MODIFY_FORM",
  "NEW_COMPONENT",
  "DELETE_COMPONENT",
  "EDIT_COMPONENT",
  "PARAM_STATE",
  "PARAM_MESSAGE",
  "PARAM_LOGGED_USER",
  "SUCCES",
  "ERROR",
  "LESS_THAN",
  "GREATER_THAN",
  "EXCLAMATION_MARK",
  "COLON",
  "COMMA",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "VALUE",
  "LITERAL"
  };
}

